#-------------------------------
# General Site Settings
title: Stephen Ajulu
logo: logo.svg # You can add own logo.
description: Ajulu's Thoughts is a Tech, Cybersecurity, Dev and Personal Development Blog


#-------------------------------
# Author Settings
author:
  name: Stephen Ajulu
  image: 01.jpg
  say-hello: Hi there, I’m <strong>Stephen Ajulu</strong>
  bio: I Design, develop, talk, and write about <strong>websites/web apps</strong>, <strong>cybersecurity</strong>, <strong>privacy</strong>, <strong>technology</strong>, <strong>dev</strong>, <strong>personal development and branding</strong>. I share tutorials, free resources and inspiration. Loves <a href="https://stephenajulu.com/links">creating</a> & learning.


#-------------------------------
# Contact links
twitter: https://twitter.com/stephenajulu # Add your Twitter handle
facebook: https://facebook.com/stephenajulu # Add your Facebook handle
dribbble: https://dribbble.com/stephenajulu # Add your Dribbble handle
instagram: https://instagram.com/stephenajulu # Add your Instagram handle
pinterest: https://pinterest.com/stephenajulu # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: ajulusthoughts # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: stephenajulu # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
